// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SqlLiteWithDotNetCore.Data;

#nullable disable

namespace SqlLiteWithDotNetCore.Data.Migrations
{
    [DbContext(typeof(SqlLiteWithDotNetCoreDbContext))]
    partial class SqlLiteWithDotNetCoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");
#pragma warning restore 612, 618
        }
    }
}
