// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SqlLiteWithDotNetCore.Infrastructure;

#nullable disable

namespace SqlLiteWithDotNetCore.Infrastructure.Migrations
{
    [DbContext(typeof(SqlLiteWithDotNetCoreDbContext))]
    [Migration("20251209110842_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");
#pragma warning restore 612, 618
        }
    }
}
